### ISSUE TITLE
Reconnect AMI

### ISSUE THREAD

**Issue by TECH7Fox** [TECH7Fox/asterisk-hass-integration#53]
I'm trying to reconnect the AMI, but I get this error when connecting again:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/asterisk/manager.py", line 456, in event_dispatch
    if callback(ev, self):
  File "/config/custom_components/asterisk/__init__.py", line 133, in <lambda>
    manager.register_event("Shutdown", lambda event, manager=manager, hass=hass, entry=entry: handle_shutdown(event, manager, hass, entry))
  File "/config/custom_components/asterisk/__init__.py", line 58, in handle_shutdown
    manager.connect(host, port)
  File "/usr/local/lib/python3.9/site-packages/asterisk/manager.py", line 487, in connect
    self.message_thread.start()
  File "/usr/local/lib/python3.9/threading.py", line 887, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once
```

`Threads can only be started once`. Tried using [manager.close](https://github.com/rdegges/pyst2/blob/288cfa28caceaded8b189f6876ed4253b2d92982/asterisk/manager.py#L498) but that doesn't seem to work. Anyone knows why? [Here](https://github.com/TECH7Fox/asterisk-hass-integration/blob/develop/custom_components/asterisk/__init__.py#L58) is the code.

I guess I could redefine manager, but I think that would get rid of all the event listeners from init and the entities.

**Comment by TECH7Fox** [comment]
Will get fixed by #57
